Repository hmcts/nfdiv-case-maintenance-service, pull requests merged in 2021-02, with the labels that each got.

#26 start the cleanup
  build.gradle
  dependency-check-suppressions.xml
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/config/HttpConnectionConfiguration.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cms-pr-26

#25 Nfdiv 415 post case endpoint
  src/functionalTest/java/uk/gov/hmcts/reform/divorce/ccd/CcdDraftCaseSubmissionTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/divorce/support/CcdSubmissionSupport.java
  src/functionalTest/java/uk/gov/hmcts/reform/divorce/support/CcdUpdateSupport.java
  src/functionalTest/java/uk/gov/hmcts/reform/divorce/support/PetitionSupport.java
  src/functionalTest/java/uk/gov/hmcts/reform/divorce/support/SubmissionUtils.java
  src/functionalTest/resources/application.properties
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/CcdDraftCaseSubmissionITest.java
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/CaseController.java
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/BaseCcdCaseService.java
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CaseService.java
  src/main/resources/application.yml
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/CaseControllerTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CaseServiceTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cms-pr-25

#28 NFDIV-415: point to common lib 1.4.4
  build.gradle
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cms-pr-28

#27 update deps
  .github/PULL_REQUEST_TEMPLATE.md
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/MockSupport.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/SearchCasesITest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/UnlinkUserITest.java
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/CaseMaintenanceServiceApplication.java
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdRetrievalServiceImpl.java
  src/main/resources/application.yml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cms-pr-27

#29 update chart
  charts/nfdiv-cms/Chart.yaml
  charts/nfdiv-cms/requirements.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cms-pr-29

#30 Add app insights
  charts/nfdiv-cms/Chart.yaml
  charts/nfdiv-cms/values.yaml
  src/main/resources/application.yml
  src/main/resources/bootstrap.yaml
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/RootControllerTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cms-pr-30

#35 Bumped chart version as previous commit was reverted which included c…
  charts/nfdiv-cms/Chart.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cms-pr-35

#36 Add get case endpoint for retrieving case with user token
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/CaseRetrievalITest.java
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/CaseController.java
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/CcdRetrievalService.java
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdRetrievalServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/CaseControllerTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdRetrievalServiceImplUTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cms-pr-36

#37 Added functional tests for get case endpoint
  src/functionalTest/java/uk/gov/hmcts/reform/divorce/petition/RetrieveCcdCaseTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/divorce/support/PetitionSupport.java
  src/functionalTest/resources/application.properties
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cms-pr-37

#39 Nfdiv 435 patch case
  src/functionalTest/java/uk/gov/hmcts/reform/divorce/ccd/DraftCaseSubmissionTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/divorce/ccd/PatchCaseTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/divorce/util/RestUtil.java
  src/functionalTest/resources/application.properties
  src/functionalTest/resources/ccd-submission-payload/initial-case-for-patch.json
  src/functionalTest/resources/ccd-submission-payload/patch-case.json
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/DraftCaseSubmissionITest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/PatchCaseITest.java
  src/integrationTest/resources/ccd-submission-payload/patch-case.json
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/CaseController.java
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/BaseCcdCaseService.java
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CaseService.java
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/UserServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/util/CaseDataUtil.java
  src/main/resources/application.yml
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/CaseControllerTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CaseServiceTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdRetrievalServiceImplUTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdSubmissionServiceImplUTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdUpdateServiceImplUTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/UserServiceImplUTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/util/CaseDataUtilTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cms-pr-39

#38 Upgrade again
  .github/PULL_REQUEST_TEMPLATE.md
  build.gradle
  charts/nfdiv-cms/Chart.yaml
  charts/nfdiv-cms/requirements.yaml
  charts/nfdiv-cms/values.yaml
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/MockSupport.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/SearchCasesITest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/UnlinkUserITest.java
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/CaseMaintenanceServiceApplication.java
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdRetrievalServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/bootstrap.yaml
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/RootControllerTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cms-pr-38

#41 Removed get case functionality as it is now available in cos
  src/functionalTest/java/uk/gov/hmcts/reform/divorce/petition/RetrieveCcdCaseTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/divorce/support/PetitionSupport.java
  src/functionalTest/resources/application.properties
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/CaseRetrievalITest.java
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/CaseController.java
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/CcdRetrievalService.java
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdRetrievalServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/CaseControllerTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdRetrievalServiceImplUTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cms-pr-41
