Repository hmcts/nfdiv-case-maintenance-service, pull requests merged in 2021-01, with the labels that each got.

#12 remove auth2 config
  src/main/resources/application.yml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cms-pr-12

#14 Use azure cli to get secrets
  .gitignore
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
  README.md
  build.gradle
  infrastructure/output.tf
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/context/ServiceContextConfiguration.java
  src/integrationTest/resources/application-aat.properties
  src/integrationTest/resources/application-saat.properties
  src/integrationTest/resources/application.properties
  src/integrationTest/resources/example-application-local.properties
  src/main/resources/example-application-aat.yml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cms-pr-14

#15 simplify the gradle bootRun and functional test tasks
  README.md
  build.gradle
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cms-pr-15

#24 Remove case formatter service
  build.gradle
  charts/nfdiv-cms/Chart.yaml
  charts/nfdiv-cms/values.yaml
  infrastructure/main.tf
  src/contractTest/resources/application.yml
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/AmendedPetitionDraftServiceITest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/AmendedPetitionForRefusalDraftFromCaseIdServiceITest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/AmendedPetitionForRefusalDraftServiceITest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/MockSupport.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/RetrieveAosCaseITest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/RetrievePetitionITest.java
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/FormatterServiceClient.java
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/management/monitoring/health/CaseFormatterServiceHealthCheck.java
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/PetitionServiceImpl.java
  src/main/resources/application.yml
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/management/monitoring/health/HealthCheckITest.java
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/PetitionServiceImplUTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cms-pr-24
